[package]
name = "rs-libc"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = true
[dependencies]
api           = {path = "api"}
# backtrace = { version = "0.3.76", default-features = false }
bitflags = "2.10.0"
cfg-if = "1.0.4"
compiler_builtins = "0.1.160"
memory        = {path = "memory"}
unwinding = { version = "0.2.8", default-features = false, features = ["fde-static","unwinder"]}
# unwind = "0.4.2"

[workspace]
members = ["crt0", "api", "api-sys","arch", "memory","libc-patch", "utils/syscall",]
default-members = [".","./crt0"]
exclude = ["tests"]

[workspace.package]
version = "0.0.0"
edition = "2024"
publish = false
# BSD-3 Clause and GPL-2.0 are compatible.

license = "BSD-3-Clause with LLVM-exception"

[build-dependencies]
cc = "1.2.46"
version_check = "0.9.5"

[features]
# This prevents pitfalls of C functions. Like adding strlen + 1
# with the downside of not following the C spec
# @TODO: Not implemented
additional-checks = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
crate-type = ["cdylib","lib","staticlib"]
harness = false
[lints]
workspace = true
# === LINTS ===

# Defaults are usually fine, but we sometimes want to be a little stricter
# Lint levels should be done with care.
# 
# Forbid: This should be handled quickly and is easy to ensure, like documenting ensuring something is safe.
#               and something that shouldn't span across multiple commits
#
# Warn  : Discouraged but has reasons to, should be cleaned up, silly mistakes
#
# Allow : A comment should always accompany explicitly allowing a lint project wide
[workspace.lints.clippy]
allow_attributes_without_reason = {level = "forbid"}
undocumented_unsafe_blocks      = {level = "forbid"}
multiple_unsafe_ops_per_block   = {level = "warn"}
dbg_macro                       = {level = "warn" } # prevents dbg being apart of a release
# These are often just wrappers around new. Especially if new takes no parameters. Just taking up code gen
new_without_default             = {level = "allow"} 
needless_return                 = {level = "allow"}
[workspace.lints.rust]
non-ascii-idents                = {level = "forbid"} # Why use non-ascii idents? Make it harder to use this code base?
unsafe-op-in-unsafe-fn          = {level = "deny"} # There a reasons on why to do this, like wrapping it around the C-abi. But most of the time it's a no
redundant-imports               = {level = "warn"}
linker-messages                 = {level = "warn"}
missing-debug-implementations   = {level = "warn"}
missing_docs                    = {level = "warn"}
redundant-lifetimes             = {level = "warn"} # better use less life times when possible
single-use-lifetimes            = {level = "warn"}

[workspace.lints.rust.unexpected_cfgs]
level = "deny" # Try to avoid typos
check-cfg = [

    'cfg(testing)'
]
