[package]
name = "memory"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
cfg-if = "1.0.4"

spin = {version = "0.10.0", default-features = false,features = ["spin_mutex"]}
api  = {path = "../api"}
# [target.'cfg(not(feature="std"))'.dependencies]

[features]
# This is 
# std = ["dep:libc"]
[lints]
workspace = true
