#ifndef _SYS_SYSCALL_H
#define _SYS_SYSCALL_H
// #include "rslibc/misc.h"

/*
    This is generated by libc

    Currently no generation is done yet, so it bootstrabs your current libc
    @TODO: create actual bits header
*/
#ifdef __GNUC__

/* Define some macros used by GCC's headers like there bits/syscall.h errors if included explicitly and not by there sys/syscall.h*/
/* @TODO: Not to rely on GCC's headers*/
#define _SYSCALL_H 1

#endif

#include <bits/syscall.h>


#endif /*__H_SYSCALL header guard*/