#ifndef _SYSCALL_H

#include "rslibc/misc.h"

/*
    This is generated by libc

    Currently no generation is done yet, so it bootstrabs your current libc
    @TODO: create actual bits header
*/
#include <bits/syscall.h>




#endif /*__H_SYSCALL header guard*/